### ISSUE TITLE
请支持armv8（IL2CPP）的build

### ISSUE THREAD

**Issue by zhaoqp** [jynew/jynew#986]
请支持armv8（IL2CPP）的build

**Comment by chris-jin** [comment]
同求支持il2cpp

**Comment by chenggongchina** [comment]
没理解，mono或il2cpp不会影响到玩家端的体验啊？

**Comment by chenggongchina** [comment]
而且自己应该可以直接打包IL2CPP的版本

**Comment by chris-jin** [comment]
多谢回复！

业余选手，尝试看看il2cpp和mono的性能比较，unity教程中简单的fps游戏在实验中几乎没有区别。
尝试手动打包jynew的il2cpp包，一直报错，主要是报的错无从查起。
步骤（v0.1.1或者main branch都试过）：
1. File->Build Settings 选择Android，选择il2cpp .net 2.0。
2. 菜单 XLua->"Generate Code"，成功执行。
3.  菜单 配置表->“Gen Data” 成功执行
4.  窗口（window）->"Assets Management"->"Addressables"->Groups ->Build 成功执行
5.  File->Build Settings ，Build 失败。

Unity 报错，某次的报错如下：
Exception: IL2CPP error for type 'UnityEngine.Scripting.PreserveAttribute' in assembly 'G:\code\jynew\jyx2\Temp\StagingArea\assets\bin\Data\Managed\UnityEngine.CoreModule.dll'
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unity.Cecil.Awesome.AssemblyQualifiedNameExtensions.TyperefAssemblyName(TypeReference typeref)
   at Unity.Cecil.Awesome.AssemblyQualifiedNameExtensions.AssemblyQualifiedName(TypeReference typeref, GenericMethodContext genericMethodContext, String suffix)
   at Unity.Cecil.Awesome.AssemblyQualifiedNameExtensions.AssemblyQualifiedName(TypeReference typeref, GenericMethodContext genericMethodContext, String suffix)
   at Unity.IL2CPP.SemiUniqueStableTokenGenerator.GenerateFor(TypeReference type)
   at Unity.IL2CPP.HashCodeCache`1.GetUniqueHash(T value)
   。。。。
UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <d1d277cb810e4868a8783aa0c63c537c>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

报的具体错误会变化，但基本都在mscore.dll或者UnityEngine.CoreModule.dll中，没有指向具体的cs文件，无法排查。

尝试只打包”GameStart“ 场景，也会出错。

**Comment by chris-jin** [comment]
> 而且自己应该可以直接打包IL2CPP的版本

或者能否提供一些guide，我来做这个IL2CPP的支持也可以。

**Comment by chenggongchina** [comment]
我已经测试过，可以il2cpp打包且正常运行。后续考虑增加guide

**Comment by chris-jin** [comment]
> 我已经测试过，可以il2cpp打包且正常运行。后续考虑增加guide

多谢，期待文档。
